### ISSUE TITLE
module declared path vs required Error on Step 5

### ISSUE THREAD

**Issue by devdudeio** [Glyphack/graphql-golang#3]
**What steps did you take and what happened:**

Hi, I am on step 5 - https://www.howtographql.com/graphql-go/5-create-and-retrieve-links/

the file `links.go` got these imports but they are not working.
```
import (
	database "github.com/glyphack/go-graphql-hackernews/internal/pkg/db/mysql"
	"github.com/glyphack/go-graphql-hackernews/internal/users"
	"log"
)
```

Error when trying to sync the dependencies
```
go: finding module for package github.com/glyphack/go-graphql-hackernews/internal/users
go: finding module for package github.com/glyphack/go-graphql-hackernews/internal/pkg/db/mysql
go: found github.com/glyphack/go-graphql-hackernews/internal/pkg/db/mysql in github.com/glyphack/go-graphql-hackernews v0.0.0-20200828124418-f7f14507bf92
go: graphql-gen-example/internal/links imports
	github.com/glyphack/go-graphql-hackernews/internal/pkg/db/mysql: github.com/glyphack/go-graphql-hackernews@v0.0.0-20200828124418-f7f14507bf92: parsing go.mod:
	module declares its path as: github.com/glyphack/graphlq-golang
	        but was required as: github.com/glyphack/go-graphql-hackernews
```

**What did you expect to happen:**
Dependencies sync should work

**Comment by jordaneaster** [comment]
I can confirm this is not working as expected with the same errors mentioned above @Glyphack 

ERROR:

        github.com/glyphack/go-graphql-hackernews/internal/pkg/db/mysql: github.com/glyphack/go-graphql-hackernews@v0.0.0-20230307061321-3e605bf25fdb: parsing go.mod:
        module declares its path as: github.com/glyphack/graphlq-golang
                but was required as: github.com/glyphack/go-graphql-hackernews

**Comment by jordaneaster** [comment]
$ go get github.com/Glyphack/graphql-golang
go: downloading github.com/Glyphack/graphql-golang v0.0.0-20230307061321-3e605bf25fdb
go: github.com/Glyphack/graphql-golang@v0.0.0-20230307061321-3e605bf25fdb: parsing go.mod:
        module declares its path as: github.com/glyphack/graphlq-golang
                but was required as: github.com/Glyphack/graphql-golang

**Comment by Glyphack** [comment]
Thanks for noticing this. This seems to be related to this line in the go module file where the module name is defined:
https://github.com/Glyphack/graphql-golang/blob/master/go.mod#LL1C1-L2C1

This needs to be changed to match how the package was imported probably.

**Comment by jordaneaster** [comment]
No problem man, you have an awesome project for those learning to connect graphql and go, like me. its def worth a shot! please do let us know when you have time to update. thanks!

**Comment by Glyphack** [comment]
I can update this today or tomorrow, should not take much time. By the way if you are reading the guide there are some improvements that can be done, don't hesitate to mention anything you see which is wrong or not clear.

**Comment by Glyphack** [comment]
Hi @devdudeio @jordaneaster I updated the tutorial to fix the incorrect module path & added the explanation on how to replace the path with your own if you are writing the project yourself.


Regarding

> $ go get github.com/Glyphack/graphql-golang
go: downloading github.com/Glyphack/graphql-golang v0.0.0-20230307061321-3e605bf25fdb
go: github.com/Glyphack/[graphql-golang@v0.0.0-20230307061321-3e605bf25fdb](mailto:graphql-golang@v0.0.0-20230307061321-3e605bf25fdb): parsing go.mod:
module declares its path as: github.com/glyphack/graphlq-golang
but was required as: github.com/Glyphack/graphql-golang

You don't need to use `go get` with this project if you are following the tutorial and building your server. You can replace the path `github.com/glyphack/graphql-golang` with `github.com/<your-project-path>` so you don't need to install this project as a dependency. This was not clear in the tutorial but I added the explanation that you need to replace this based on your project path.

**Comment by jordaneaster** [comment]
Amazing thank you!
