### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by McCdama** [Glyphack/graphql-golang#5]
Hey thanks for the tutorial.

I would like to know if there is any way to escape using Docker on this site:

https://www.howtographql.com/graphql-go/4-database/

thanks in advance.
regards

**Comment by Glyphack** [comment]
Yes you can locally setup a mySQL instance and use it's address as URL. For
setting it up there are many guides.

**Comment by McCdama** [comment]
thanks for replying.. I'll give it a shot.
