### ISSUE TITLE
Gqlgen latest v0.17.13 doesn't use chi

### ISSUE THREAD

**Issue by DivyanshuBhoyar** [Glyphack/graphql-golang#7]
A noob here, just found that that gqlgen generate  command generate server.go with vanilla net/http handlers, without chi.
What changes should I make for the auth.middleware() to work without chi ?

**Comment by Glyphack** [comment]
Hi, If I remember correctly, gqlgen never generated a project with the chi handler. You need to install chi and import the router just like how it's done in `server.go`.
Also, here's the original document from gqlgen:
https://gqlgen.com/recipes/authentication/
